### ISSUE TITLE
Please publish a crate

### ISSUE THREAD

**Issue by erickt** [kbknapp/cargo-outdated#10]
This project is cool! Now that `cargo install` works, if this was published as a crate, we could use `cargo install cargo-outdated` to install the project.

**Comment by kbknapp** [comment]
This needs some updates first to get it working correctly again, see #6 

Once I get some additional time to work on this issue, I'll publish a crate for `cargo install` :smile:

**Comment by kbknapp** [comment]
Ah, and I actually didn't see the latest comment....publishing a crate now :+1:
