### ISSUE TITLE
False warnings for obsolete features

### ISSUE THREAD

**Issue by shssoichiro** [kbknapp/cargo-outdated#100]
I have a crate that depends on chrono, diesel, uuid, and serde. These each need certain features enabled in order to work together, e.g. from `Crate.toml` (simplified):

```
[dependencies.diesel]
features = [
    "postgres",
    "chrono",
]
version = "0.16.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies]
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
```

With cargo-outdated 0.6.2, running `cargo outdated` on this crate produces the following warnings:

```
warning: Feature serde of package chrono has been obsolete in version 0.4.0
warning: Feature chrono of package diesel has been obsolete in version 0.16.0
warning: Feature uuid of package diesel has been obsolete in version 0.16.0
warning: Feature serde_json of package diesel has been obsolete in version 0.16.0
warning: Feature uuid of package rocket_contrib has been obsolete in version 0.3.3
warning: Feature serde of package uuid has been obsolete in version 0.5.1
```

However, removing these features causes the crate to fail to compile. `cargo outdated` should not be producing these warnings if the feature exists on the target version of the dependency.

**Comment by oherrala** [comment]
I have probably the same issue in our multicrate project. Simplified example:

Root `Cargo.toml`:

```
[workspace]
members = [ "dummylib", "dummybin" ]
```

`dummylib/Cargo.toml`:

```
[package]
name = "dummylib"

[dependencies]
quickcheck = { version = "*", optional = true }
```

`dummybin/Cargo.toml`:

```
[package]
name = "dummybin"

[dependencies]
dummylib = { path = "../dummylib" }

[dev-dependencies]
dummylib = { path = "../dummylib", features = ["quickcheck"] }
```

```console
$ cargo outdated
warning: Feature quickcheck of package dummylib has been obsolete in version 0.1.0
warning: Feature quickcheck of package dummylib has been obsolete in version 0.1.0
error: no matching version `^0.4.2` found for package `quickcheck` (required by `dummylib`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.4.1, 0.4.0, 0.3.2, ...
```

Maybe the quickcheck version error is worth another issue?

**Comment by Frederick888** [comment]
@shssoichiro Haven't got time to actually look into it but it seems that [`Summary::features()`](https://docs.rs/cargo/0.22.0/cargo/core/summary/struct.Summary.html#method.features) does not include optional dependencies by default hence the false warnings.

---

@oherrala Due to the fact that [`quickcheck`](https://crates.io/crates/quickcheck) has been yanked. Could you please file another issue?
