### ISSUE TITLE
Unable to update registry behind proxy

### ISSUE THREAD

**Issue by aleksander** [kbknapp/cargo-outdated#103]
`cargo outdated` command failed in case of connection through proxy server:

> error: failed to load source for a dependency on `byteorder`
> Caused by:
>   Unable to update registry https://github.com/rust-lang/crates.io-index
> Caused by:
>   failed to fetch `https://github.com/rust-lang/crates.io-index`
> Caused by:
>   [12/-16] proxy authentication required, but no callback provided
>

**Comment by Frederick888** [comment]
It looks like an error from `cargo` itself. So all other `cargo` functionalities are fine except `cargo outdated`? I don't even know that `cargo` can be configured with a proxy. Could you please give more details?

**Comment by aleksander** [comment]
Strange, but I can't reproduce it. Sorry for the noise.

**Comment by Frederick888** [comment]
No worries :)
