### ISSUE TITLE
Always fails with "Invalid arguments." on nightly 2018-03-19

### ISSUE THREAD

**Issue by niklasf** [kbknapp/cargo-outdated#128]
Regardless of actual arguments:

```
$ cargo outdated --help
Invalid arguments.

USAGE:
    cargo outdated [options]
```

**Comment by kjeremy** [comment]
I'm Seeing this on Ubuntu 16.04.

**Comment by valff** [comment]
It isn't specific to `cargo-outdated`, all external subcommands affected. Looks like the issue is already fixed: rust-lang/cargo@deb1c1e15c972d713e723088516b02a23e9bac8e.

**Comment by Frederick888** [comment]
As mentioned by @valff, this issue comes upstream from `cargo`, and it's to be fixed by rust-lang/rust#49182.

But I'd like to keep this ticket open until the problem is gone so we could test it again.

**Comment by mbilker** [comment]
Current workaround is to run `cargo outdated outdated`.

**Comment by kbknapp** [comment]
Yeah either use `cargo outdated outdated` or use the stable channel. Since it's fixed upstream it should appear in one of the next nightlies

**Comment by niklasf** [comment]
Thanks all. It has indeed been fixed.

**Comment by kbknapp** [comment]
It's made it out into the latest nightly.

So others finding this issue, the fix is `rustup update nightly`
