### ISSUE TITLE
Direct dependency quicli not found for package commit-msg-gen

### ISSUE THREAD

**Issue by dineshadepu** [kbknapp/cargo-outdated#137]
Hi,

I am checking the outdated packages in [quicli](https://github.com/killercup/quicli), but I get this error

```rust
dinesh@Personal (master *) /home/dinesh/prog/rust/quicli $  
|  Personal desktop => cargo outdated
error: Direct dependency quicli not found for package commit-msg-gen
```

**Comment by jonhoo** [comment]
This is probably a duplicate of either https://github.com/kbknapp/cargo-outdated/issues/167 or https://github.com/kbknapp/cargo-outdated/issues/126. It'd probably be good if `cargo-outdated` could provide a more verbose error message for these situations.

**Comment by deg4uss3r** [comment]
I believe this issues was resolved when updating `cargo` as a dependency. Please open a new issue with a failing `Cargo.toml` if this is not the case.
