### ISSUE TITLE
Make it easier to integrate with CI

### ISSUE THREAD

**Issue by eduardobraun** [kbknapp/cargo-outdated#144]
It would be nice if when there are outdated crates the program would return an error.

This way one would be able to create a CI stage that verifies if all crates are up-to-date (without the need to parse the result). So projects would be able to enforce that every merge request updates the dependencies before being accepted or run the stage nightly, which would probably reduce the number of multiple versions of the same crate.

It would also require a way to ignore some crates, something like `# OUTDATED: some reason` on the line above the dependency in the Cargo.toml.

**Comment by kraai** [comment]
I think you can do this already by using `--exit-code 1`.  That was supposed to fix #23, which this seems to be a duplicate of.

**Comment by eduardobraun** [comment]
Yes its a duplicate, I completely missed this argument. Sorry.
