### ISSUE TITLE
Failed to parse manifest error when using thin lto

### ISSUE THREAD

**Issue by drrlvn** [kbknapp/cargo-outdated#147]
My `Cargo.toml` contains the following:

```
[profile.release]
lto = "thin"
```

And when I run `cargo outdated` I get the following error:

```
error: failed to parse manifest at `/home/drorl/dev/host-io/Cargo.toml`

Caused by:
  invalid type: string "thin", expected a boolean for key `profile.release.lto`
```

Note that this is valid as per https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections - `lto` can be a boolean or a string.

**Comment by deg4uss3r** [comment]
I believe this has been resolved by bumping `cargo` dependency.

It works for me on MacOS 10.15.5 with `cargo-outdated` `v0.9.10' (and the upcoming `v0.9.11`) using the following `Cargo.toml`:

```
[package]
name = "lto-test"
version = "0.1.0"
authors = ["degausser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "=0.17.0-alpha.1"

[profile.release]
lto = "thin"

[profile.dev]
lto = "fat"
```
