### ISSUE TITLE
Publish 0.7.1 tag & release

### ISSUE THREAD

**Issue by gyscos** [kbknapp/cargo-outdated#148]
Hi!
Now that 0.7.1 was published on crates.io, could you push a tag for it, and maybe set up a github release? This helps packaging for distributions.
Thanks!

**Comment by Cogitri** [comment]
FWIW, you can download from crates.io too: https://static.crates.io/crates/cargo-outdated/cargo-outdated-0.7.1.crate

**Comment by kornelski** [comment]
I've added a tag
