### ISSUE TITLE
Can't run with cargo nightly features

### ISSUE THREAD

**Issue by est31** [kbknapp/cargo-outdated#154]
Cargo-outdated can't run if I'm using cargo nightly features.
E.g. put this into your Cargo.toml ([profile-overrides](https://github.com/rust-lang/rust/issues/48683) feature):
```toml
cargo-features = ["profile-overrides"]
```

Then you'll get this by Cargo-outdated:
```
error: failed to parse manifest at `Cargo.toml`

Caused by:
  the cargo feature `profile-overrides` requires a nightly version of Cargo, but this is the `dev` channel
```

**Comment by kornelski** [comment]
Yes, that's an unfortunate limitation of bundling own cargo version as a library.

**Comment by est31** [comment]
Nevermind... that doesn't work.

What's needed is calling `maybe_allow_nightly_features` I think: https://docs.rs/cargo/0.32.0/cargo/core/fn.maybe_allow_nightly_features.html

**Comment by est31** [comment]
Okay, that works. @kornelski made a PR: #155
