### ISSUE TITLE
Automatically upload tagged releases to crates.io in CI

### ISSUE THREAD

**Issue by drrlvn** [kbknapp/cargo-outdated#158]
Currently release v0.8.0 is not on crates.io because [@kbknapp is busy](https://github.com/kbknapp/cargo-outdated/pull/153#issuecomment-449982916).

This would not be an issues if tagged releases were automatically uploaded to crates.io by CI.

Note that it also means that permissions don't need to be managed in multiple places.

**Comment by Dylan-DPC** [comment]
Thanks. Though I am not favour in automating crates,io releases since it could be a risk going forward.

**Comment by est31** [comment]
It would be nice to be able to have push-only tokens that can only publish for one of your crates.io crates, but nothing more. Similar to GitHub deploy keys.

**Comment by Nemo157** [comment]
@est31 yes! See https://github.com/rust-lang/crates.io/issues/849 for the upstream issue to enable that.

**Comment by deg4uss3r** [comment]
Since the goal will be the get `cargo-outdated` into `cargo` as a built in. Until then I'll tag and update versions to crates.io myself for bug fixes. :)
