### ISSUE TITLE
Inconsistent output

### ISSUE THREAD

**Issue by TimNN** [kbknapp/cargo-outdated#17]
Running `cargo outdated` multiple times can produce a different **number** of outdated dependencies:

```
$ cargo outdated                             
Checking for SemVer compatible updates...Done
Checking for the latest updates...Done
The following dependencies have newer versions available:

    Name                     Project Ver  SemVer Compat  Latest Ver
    handlebars->quick-error     0.1.4          --          0.2.2
    quick-error                 0.2.2        0.1.4           --
$ cargo outdated                       
Checking for SemVer compatible updates...Done
Checking for the latest updates...Done
The following dependencies have newer versions available:

    Name                     Project Ver  SemVer Compat  Latest Ver
    handlebars->quick-error     0.1.4        0.2.2         0.2.2
```

The `Cargo.*` files which produce this output can be found in [this gist](https://gist.github.com/TimNN/3064d6a5c780870f965d).

**Comment by TimNN** [comment]
I've been looking at this again and the second line of the first output doesn't even make sense since `0.1.4` is older than `0.2.2` so why is it reported as `SemVer Comppat`?

Could it be possible that whether this issue manifests itself or not depends on whether `quick-error` or `handlebars->quick_error` is processed first?

**Comment by TimNN** [comment]
I've reduced the size of the `Cargo.*` files a little and collected the output of running with the `debug` feature and verbose for both cases, the data is again in [a gist](https://gist.github.com/TimNN/f63110a74a83d4540443).

**Comment by Frederick888** [comment]
I deem that this has been fixed in the new release, i.e. `0.4.0`. Could you please test it again?

**Comment by TimNN** [comment]
I don't think I can easily test again, since the versions of the involved crates have changed a lot, however I have no problem with closing this issue for now.
