### ISSUE TITLE
the `default-run` manifest key is unstable

### ISSUE THREAD

**Issue by lzutao** [kbknapp/cargo-outdated#173]
But `default-run` is stable since Rust v1.37.0. What else do we need to make it work?

**Comment by kornelski** [comment]
`cargo-outdated` needs to depend on a newer version of Cargo.

Alternatively, use https://lib.rs/cargo-upgrades that uses system's Cargo.

**Comment by lzutao** [comment]
Thanks, so we need new version of cargo crate.
About `cargo-upgrades`, I tried it, but it didn't work correctly like cargo-outdated.
