### ISSUE TITLE
Honor `.cargo/config` configuration

### ISSUE THREAD

**Issue by d-e-s-o** [kbknapp/cargo-outdated#183]
It appears that the program does not honor `.cargo/config` as `cargo` itself does.

I have a private Git based project that is fetched over SSH. In order to do so I use an SSH alias. Cargo's git support does not honor SSH aliases and so I have the following in `<project>/.cargo/config:
```toml
[net]
git-fetch-with-cli = true
```
That instructs `cargo` to fall back to using the `git` CLI application itself, which honors SSH aliases as one would expect.

`cargo-outdated`, however, does not work in such a setup as it seemingly does not honor `.cargo/config`.

**Comment by deg4uss3r** [comment]
Hi @d-e-s-o I'd like to look into this issue, but have never used SSH aliases for git and cargo, could you walk me through a simple test setup so I can see this and the errors locally (well, local enough to test the fetch over ssh)?

**Comment by d-e-s-o** [comment]
Sure thing. The following steps assume sshd running on port 22 (the default) and
public key authentication enabled (also the default, I believe).

```bash
# For the sake of illustration, let's use public key authorization for
# SSHing into our own system.
# Start by generating a key.
$ ssh-keygen -t ed25519 -o -f ~/.ssh/"user@home_$(date '+%Y-%m-%d')"
> Generating public/private ed25519 key pair.
> Enter passphrase (empty for no passphrase): <empty>
> Enter same passphrase again: <empty>
> Your identification has been saved in ~/.ssh/user@home_2019-12-18.
> Your public key has been saved in ~/.ssh/user@home_2019-12-18.pub
# Make it known.
$ cat ~/.ssh/user@home_2019-12-18.pub >> ~/.ssh/authorized_keys
# Now let's create our alias, 'home', that uses said key pair.
$ cat <<EOF >> ~/.ssh/config
Host home
  User user
  Hostname localhost
  IdentityFile ~/.ssh/user@home_2019-12-18
EOF
# Verify that the alias works.
$ ssh home echo yippie ki-yay
> yippie ki-yay

# Let's create a cargo library that we will later depend on.
$ cd /tmp
$ cargo init --lib bar
$ cd !$
$ cat <<EOF > src/lib.rs
pub fn bar() {
  println!("Hello from bar");
}
EOF
$ git add .
$ git commit --message "Initial commit"

# Now create the binary depending on the library.
$ cd /tmp
$ cargo init --bin foo
$ cd !$
# Add `bar` referenced through our SSH alias `home` as a dependency.
$ echo 'bar = {git = "ssh://home/tmp/bar"}' >> Cargo.toml

# As I mentioned that won't be enough:
$ cargo build
>     Updating git repository `ssh://home/tmp/bar`
> warning: spurious network error (2 tries remaining): failed to resolve address for home: Name or service not known; class=Net (12)
> warning: spurious network error (1 tries remaining): failed to resolve address for home: Name or service not known; class=Net (12)
> error: failed to load source for a dependency on `bar`
>
> Caused by:
>   Unable to update ssh://home/tmp/bar
>
> Caused by:
>   failed to clone into: /home/user/.cargo/git/db/bar-c375823edfef5474
>
> Caused by:
>   failed to resolve address for home: Name or service not known; class=Net (12)
# Let's fix that.
$ mkdir .cargo
$ cat <<EOF >> .cargo/config
[net]
git-fetch-with-cli = true
EOF
$ cargo build
>    Updating git repository `ssh://home/tmp/bar`
>   Compiling bar v0.1.0 (ssh://home/tmp/bar#712652b1)
>   Compiling foo v0.1.0 (/tmp/foo)
>    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
# There you go!
```

**Comment by deg4uss3r** [comment]
Great write up, I hope to get this setup and testing soon. Will keep this thread updated.

**Comment by deg4uss3r** [comment]
Okay so I found out a few things: 
1) There was no tracking of the `[net]` sections so I [added that](https://github.com/deg4uss3r/cargo-outdated/blob/networking_addition/src/cargo_ops/mod.rs#L50) to the `Manifest` struct. 
2) The update was not checking the `Cargo.toml` in this way, but rather updating the `Cargo.lock` file [here](https://github.com/deg4uss3r/cargo-outdated/blob/networking_addition/src/cargo_ops/temp_project.rs#L160) 
3) If you had set the environmental variable `CARGO_NET_GIT_FETCH_WITH_CLI` to `true`, it works! So, I look for the configuration in the `[net]` section and added that to the environment before we create the config for the lock file [here](https://github.com/deg4uss3r/cargo-outdated/blob/networking_addition/src/cargo_ops/temp_project.rs#L79-L85)

I plan on creating a WIP PR and discussing whichever else we might need to add and set in the `$ENV` to pull all packages from various configurations.

**Comment by d-e-s-o** [comment]
Great stuff. Thank you!
