### ISSUE TITLE
https_proxy defined in environment is not used

### ISSUE THREAD

**Issue by huxi** [kbknapp/cargo-outdated#191]
A proxy defined via `https_proxy` environment variable isn't used.
Instead, the following error message is produced after timeout has been reached:

```text
Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to connect to github.com: Operation timed out; class=Os (2)
```

In contrast, `cargo update` honors the defined proxy.

**Comment by deg4uss3r** [comment]
Hello @huxi I am looking into this, you are correct it doesn't seem to be honoring the proxy for some reason. The full environment is indeed passed to the cargo function`update_lockfile(...)` via cargo_outdated's `.cargo_update(...)`, I wondering if the API changed slightly and there need to be an option we call to honor the networking environmental variables during the lockfile update.

**Comment by deg4uss3r** [comment]
Found the error! We need to bump our `cargo` dependency to `0.41` I have it working on my local machine but there were some slight changes I need to test and have a few too many `.unwrap()`s to call it good yet :)

**Comment by huxi** [comment]
I like that the root of the problem was an **outdated** dependency. :)
Thanks for the quick response & fix!
