### ISSUE TITLE
Updated git release tags

### ISSUE THREAD

**Issue by bhipple** [kbknapp/cargo-outdated#206]
The last tagged release appears to be 0.8.0, while crates.io has up to 0.9.5.  While many users may just run `cargo install`, it's useful for users building from source to have a git tag that corresponds with the release. Moreover, distribution packaging generally builds from src and needs to know which commit to checkout.

Can we add the git release tag for whichever commit produces 0.9.5?

**Comment by bhipple** [comment]
Actually, I managed to find it by downloading and unzipping the create, which includes a cargo vsc info json file that says the git commit for 0.9.5 is 7685da3265749bb7ae2b436a132f51d19b409bff.  Even though this information can be discovered by round-tripping through crates.io, it'd still be nice to have it on git.

**Comment by deg4uss3r** [comment]
Done! Going forward we hope to be better about this. Thanks for putting this in!
