### ISSUE TITLE
Don't ignore CARGO_HOME if defined

### ISSUE THREAD

**Issue by gdesmott** [kbknapp/cargo-outdated#211]
#200 has been implemented as a workaround to not break `outdated` if env variable `CARGO_HOME` is defined.
It works fine but it's a bit unfortunate as all dependencies are now re-downloaded when running `outdated`. This is specially hurting CI jobs which generally have to redefine `CARGO_HOME` to be able to cache dependencies crates.

**Comment by deg4uss3r** [comment]
Thanks for putting this in, when GitHub auto-closed the issue, and I forgot to open a new tracking issue to help fix this!

**Comment by deg4uss3r** [comment]
Hi @gdesmott could you test my [branch](https://github.com/deg4uss3r/cargo-outdated/commit/f89065105dc7325e19bac88fb2c62b19fde48e35) that fixes this please? I works for me locally, but I want to make sure this works in a CI environment or if you can mimic that it would be really helpful before I PR and merge. 

Thank you!!

**Comment by gdesmott** [comment]
@deg4uss3r : that [didn't work](https://gitlab.freedesktop.org/gdesmott/karapulse/-/jobs/2051876). It re-downloaded deps and failed to find some.

**Comment by deg4uss3r** [comment]
Thanks for testing that @gdesmott! 

When testing locally it seems to understand if the directory exists, and does not download the dependencies again. Also if the directory doesn't exist, it will create it! I tested on MacOS (Mojave) and Ubuntu. The only error I got was if I tried to write to the root directory as if your `${CI_PROJECT_DIR}` variable was empty and got:

`error: failed to create directory '//build/target/cargo_home/registry/index/github.com-1ecc6299db9ec823'`

Is there anything I am not taking into account here? I believe I'm missing something that would cause these errors but I cannot see it myself!

**Comment by gdesmott** [comment]
No that's really strange, my `CARGO_HOME` is defined as `"${CI_PROJECT_DIR}/build/target/cargo-home/"`  which seems to work for the other jobs so I guess it's correct.

**Comment by deg4uss3r** [comment]
@gdesmott I'm stumped! Could you try to verify locally, so it's not just me? I think this might be CI is a different configuration.

**Comment by gdesmott** [comment]
That doesn't seem to work either:

```
$ CARGO_HOME=my-cargo cargo outdated
Update for sval could not be found!
Update for reqwest could not be found!
Update for trybuild could not be found!
Update for trybuild could not be found!
```

Here is how I installed your branch. Is this the proper way?
`cargo install --git https://github.com/deg4uss3r/cargo-outdated.git --branch cargo_home`

**Comment by deg4uss3r** [comment]
Hmm it looks like this is happening for the optional/dev dependencies of other dependencies.. I need to look into this thanks for bringing this to my attention!

**Comment by deg4uss3r** [comment]
@gdesmott I believe I found the issue if you'd like to retest :) Turns out it's finding the `toml` files recursively in the directory if the `$CARGO_HOME` variable is set within the project directory causing those `Update for {} could not be found!` issues. 

Let me know if this is still failing, but it appears to be downloading to the specified `$CARGO_HOME` and not re-downloading if it already exists in the path provided!

**Comment by gdesmott** [comment]
It works, both locally and on CI! :+1: 
Thanks for your work on this.
