### ISSUE TITLE
Checkbox in CLI like npm-check

### ISSUE THREAD

**Issue by frederikhors** [kbknapp/cargo-outdated#215]
Thanks for your work!

It would be amazing to have something like https://github.com/dylang/npm-check for this amazing project!

![image](https://user-images.githubusercontent.com/41120635/78078977-7bb0af00-73ab-11ea-9349-ae10440c35eb.png)

**Comment by deg4uss3r** [comment]
Hi @frederikhors Thank you very much for the issue! I lean towards keeping this a CLI vs TUI application for simplicity sake. `cargo-outdated` has always stated it is simply a report tool you run for finding out-of-date dependencies.
