### ISSUE TITLE
v0.9.9 fails to parse manifest: no targets specified in the manifest

### ISSUE THREAD

**Issue by helaan** [kbknapp/cargo-outdated#219]
After updating to v0.9.9 I started to get the following error message when running `cargo outdated`:

```
error: failed to parse manifest at `/tmp/cargo-outdated4rznqo/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

My Cargo.toml can be found here: https://dev.henkvdlaan.com/diffusion/STRATUM/browse/master/Cargo.toml . As you can see, no [lib] or [[bin]] section is present, but `src/main.rs` exists. I don't have CARGO_HOME defined.

I bisected my changes and landed on this commit: https://github.com/kbknapp/cargo-outdated/commit/3b2aa268518a820d94f153928de9949e5cb4e4d2

**Comment by deg4uss3r** [comment]
Thanks for the issue @helaan I am able to run your `Cargo.toml` okay with `cargo outdated` `v0.9.9` on MacOS. Can you tell me a little more about your environment? 

I also did not set `$CARGO_HOME`:

```
degausser on mac in ~/code/rust_experiments/cargo_home_fail
[:master]> cargo outdated -v
  Parsing... current workspace
Resolving... current workspace
  Parsing... compat workspace
 Updating... compat workspace
    Updating crates.io index
Resolving... compat workspace
  Parsing... latest workspace
 Updating... latest workspace
    Updating crates.io index
Resolving... latest workspace
Resolving... package status
 Printing... list format
All dependencies are up to date, yay!

degausser on mac in ~/code/rust_experiments/cargo_home_fail
[:master]> echo $CARGO_HOME


degausser on mac in ~/code/rust_experiments/cargo_home_fail
[:master]> cat ./Cargo.toml
[package]
name = "ngstratum"
version = "0.1.0"
authors = ["Henk van der Laan <opensource@henkvdlaan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Enable some macros that reduce compile time, for example by reducing the amount of trait objects.
# This may increase the running time and should not be enabled in release builds
fast-compile = []

[dependencies]
anyhow = "1"
argon2rs = "0.2"
askama = "0.9"
chrono = { version = "0.4", features = ["serde"] }
#diesel = { version = "1", features = ["chrono", "postgres", "r2d2", "uuidv07"] }
dotenv = "0.15"
futures = "0.3"
lazy_static = "1"
listenfd = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
r2d2 = "0.8"
rand = "0.7"
#refinery = "0.2"
serde = {version = "1", features = ["derive"] }
sqlx = {version = "0.3", default-features = false, features=["runtime-tokio", "macros", "chrono", "uuid", "postgres", "tls"]}
timeago = "0.2"
tokio = { version = "0.2", features = ["macros"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
warp = "0.2"

# Enable higher opt-level for some proc-macro crates to speed up compile time
[profile.dev.package.askama_derive]
opt-level = 3
[profile.dev.package.askama_shared]
opt-level = 3
[profile.dev.package.sqlx]
opt-level = 3
[profile.dev.package.sqlx-core]
opt-level = 3
[profile.dev.package.sqlx-macros]
opt-level = 3
```

**Comment by helaan** [comment]
Ok, the repository may be a red herring. I ran `cargo outdated` on this repo and got 
```
error: failed to parse manifest at `/tmp/cargo-outdated44MUdg/Cargo.toml`

Caused by:
  can't find `cargo-outdated` bin, specify bin.path
```

So a bit more about my environment:
OS: Gentoo Linux
Rust version: rustc 1.42.0 (from source), rust 1.41.1 (from binary)

I bisected using 1.42.0, I tried the 1.41.1 compiler on both amd64 and aarch64, both combinations don't work on 0.9.9.

**Comment by deg4uss3r** [comment]
Thanks for the info @helaan I'll look into this as soon as I can!

**Comment by Stunkymonkey** [comment]
same error on arch-linux

**Comment by infinity0** [comment]
Same error on Debian

**Comment by anthraxx** [comment]
I have found that using the very same rust version (1.42.0 in my case) via rustup instead of building from source (by using system package) works. Somewhere there seems to be a difference in the environment leading to this.

**Comment by kyrias** [comment]
It only works because rustup's shims always sets `CARGO_HOME`.

As linked earlier, the bug is here: https://github.com/kbknapp/cargo-outdated/commit/3b2aa268518a820d94f153928de9949e5cb4e4d2#diff-eb3c13e0392e1efb496ff86d829d78caR663

If `CARGO_HOME` is not set you're checking whether the path starts with an empty string, which is always true, so the manifest path is never added to the list of paths unless `CARGO_HOME` is set.

**Comment by anthraxx** [comment]
doh, i overlooked the mentioned bisect :joy_cat:

**Comment by deg4uss3r** [comment]
Hey everyone, sorry it took a while...day job has been a little rough these past few weeks. I have a patch in [deg4uss3r/cargo_home_fix](https://github.com/deg4uss3r/cargo-outdated/blob/cargo_home_fix/src/cargo_ops/temp_project.rs#L657:L666), unfortunately I cannot recreate the issue on MacOS or an Ubunutu VM, could one of you affected by this let me know if this works? If so I can merge and release today sometime. 

Thanks for your help and patience!!

**Comment by kyrias** [comment]
That fix is the opposite of what's required. 
It needs to be  `cargo_home_path.is_none() ||`, but you might want to keep that as a separate variable.

And how did you install the rust versions you tried to reproduce with?

**Comment by kyrias** [comment]
Actually, even that isn't correct as it doesn't handle `CARGO_HOME` being set to an empty string.

```rust
let cargo_home_path = match std::env::var_os("CARGO_HOME") {
    Some(path) if !path.is_empty() =>
        Some(path.into_string().expect("Error getting string from OsString")),
    _ => None,
};

if pkg_path.starts_with(workspace_path) {
    if cargo_home_path.is_none() || !pkg_path.starts_with(&cargo_home_path.unwrap()) {
        manifest_paths.push(pkg.manifest_path().to_owned());
    }
}
```

**Comment by deg4uss3r** [comment]
Thanks @kyrias fixed!! This is why I should always add in the comments before asking for a review  XD 

Let me know if this passes, sorry I must have `rust` installed via `rustup` on my VM (I didn't think I did), Unfortunately I won't have time today to change that.

**Comment by kyrias** [comment]
That works, yes.  (Though `s/all all/add all/`, and `unwrap` would be fine there since after `is_none() ||` we know that it can only be `Some`.)

You can use versions installed using `rustup`, you just have to invoke it directly rather than through the `rustup` shims.  E.g. `CARGO_HOME= ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo outdated`.

**Comment by deg4uss3r** [comment]
Tagged, and released. Thanks everyone for the issue, help, and patience!
