### ISSUE TITLE
Crash on alpha version

### ISSUE THREAD

**Issue by jonhoo** [kbknapp/cargo-outdated#225]
Create a new, empty crate, and add
```toml
[dependencies]
nom = "6.0.0-alpha.1"
```
Run `cargo update`, then `cargo outdated`. This gives:
```
thread 'main' panicked at 'Cannot find matched versions of package nom from source registry `https://github.com/rust-lang/crates.io-index`', /home/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-outdated-0.9.10/src/cargo_ops/temp_project.rs:377:17
```

**Comment by deg4uss3r** [comment]
Hey Jon :) 

This is because nom is listed on crates.io as `6.0.0-alpha1` not `6.0.0-alpha.1` 

If we parse this with semver: 

```
op: Compatible, major: 6, minor: Some(0), patch: Some(0), pre: [AlphaNumeric("alpha"), Numeric(1)]
```

and without the `.` we see: 

```
op: Compatible, major: 6, minor: Some(0), patch: Some(0), pre: [AlphaNumeric("alpha1")] }] })
```


Which doesn't exist in the repository (since we cannot compare `6.0.0-alpha1` with `6.0.0-alpha.1`).

**Comment by jonhoo** [comment]
Oh, that's funny, I didn't even notice, good catch!

Not sure there's much `cargo outdated` can do here, though it'd maybe be nice if it at least didn't crash? :sweat_smile:

**Comment by andy128k** [comment]
@deg4uss3r Another example:

Cargo.toml has `actix-web = "3.0.0-alpha.1"` and Cargo.lock has `actix-web = "3.0.0-beta.1"`.

`cargo outdated` panics with the same error.

**Comment by andy128k** [comment]
@deg4uss3r your version of cargo-outdated produces following warning

```
warning: cannot compare actix-web crate version found in toml ^3.0.0-alpha.1 with crates.io latest 3.0.0-beta.1
```

**Comment by deg4uss3r** [comment]
Thanks @andy128k but I am not seeing the crash on either version.. 

here's my `Cargo.toml`: 

```
[package]
name = "test_aw"
version = "0.1.0"
authors = ["degausser"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "=3.0.0-alpha.1"
```

Here's the package in `Cargo.lock`:

```
[[package]]
name = "actix-web"
version = "3.0.0-alpha.1"
```

And the output from the current `cargo-outdated`:

```
❯ cargo outdated -d 1
Name       Project        Compat  Latest        Kind    Platform
----       -------        ------  ------        ----    --------
actix-web  3.0.0-alpha.1  ---     3.0.0-beta.1  Normal  ---
```

Output from my branch which I hope to push and tag today: 

```
❯ cargo outdated -d 1
Name       Project        Compat  Latest        Kind    Platform
----       -------        ------  ------        ----    --------
actix-web  3.0.0-alpha.1  ---     3.0.0-beta.1  Normal  ---
```

Can you share you Cargo.toml?

**Comment by andy128k** [comment]
@deg4uss3r I rechecked with current master branch. It doesn't crash anymore.
[Here is a repo](https://github.com/andy128k/cargo-outdated-issue-225) where cargo outdated prints warning.
