### ISSUE TITLE
Add --exclude option

### ISSUE THREAD

**Issue by xd009642** [kbknapp/cargo-outdated#226]
So I've got an instance where cargo-outdated reports there's an outdated dependency in my crate but that dependency released a regression that stops it building on my OS. I was wondering if there was potential for an exclude option as I'm also using the --exit-code option and would rather ignore that dependency and still have my CI fail if the other dependencies are out of date

**Comment by deg4uss3r** [comment]
Possibly could be solved with solution to #223 as well
