### ISSUE TITLE
Exit Codes

### ISSUE THREAD

**Issue by hoodie** [kbknapp/cargo-outdated#23]
Hey there,
I was thinking about using this in CI. Would it be possible to add an argument so that `cargo outdated` exits with `1`?

Thank you so much

**Comment by kbknapp** [comment]
@hoodie do you mean exits with a `1` always, only if new versions exist, or just on error?

**Comment by hoodie** [comment]
Perhaps have a test mode, that exits with 1 if there is a newer version.

**Comment by kbknapp** [comment]
#24 provides a `--exit-code <num>` which allows specifying an exit code upon new versions detected.
