### ISSUE TITLE
Collision error when running cargo outdated

### ISSUE THREAD

**Issue by OskarPersson** [kbknapp/cargo-outdated#230]
(Originally created here https://github.com/rust-lang/cargo/issues/8521)

**Problem**
When running `cargo outdated` with the dependencies described below, a collision error occurs. `cargo build`, `cargo update` and all other commands I've tested works as expected.

```
$ cargo outdated
error: failed to select a version for `redis-async`.
    ... required by package `actix-redis v0.8.2`
    ... which is depended on by `outdated-redis v0.1.0 (/var/folders/x6/y9my30zs0sgbv71fl1pp0p000000gn/T/cargo-outdatedAIRVg9)`
versions that meet the requirements `= 0.6.2` are: 0.6.2

all possible versions conflict with previously selected packages.

  previously selected package `redis-async v0.6.3`
    ... which is depended on by `outdated-redis v0.1.0 (/var/folders/x6/y9my30zs0sgbv71fl1pp0p000000gn/T/cargo-outdatedAIRVg9)`

failed to select a version for `redis-async` which could resolve this conflict
```

**Steps**
1. Create a new project (`cargo new outdated-redis`) and add the following dependencies to Cargo.toml:
```
actix-redis = "0.8.2"
redis-async = "0.6.2"
```

2. Run `cargo outdated`

**Notes**

`cargo outdated --version`:
v0.9.10

`cargo version`:
cargo 1.45.0 (744bd1fbb 2020-06-15)

`rustc --version`
rustc 1.45.0 (5c1f21c3b 2020-07-13)

**Comment by deg4uss3r** [comment]
This is a difficult one because I would almost agree this is a `cargo` feature not bug. Essentially this is the same as a `Cargo.toml` like: 

```toml
[package]
name = "collision"
version = "0.1.0"
authors = ["degausser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-redis = "0.8.2"
redis-async = "0.6.3"
```

Which if you try to run `cargo build` you'll get the same error:

```
❯ cargo build
    Updating crates.io index
error: failed to select a version for `redis-async`.
    ... required by package `actix-redis v0.8.2`
    ... which is depended on by `collision v0.1.0 (/Users/rth/code/rust_experiments/collision)`
versions that meet the requirements `=0.6.2` are: 0.6.2

all possible versions conflict with previously selected packages.

  previously selected package `redis-async v0.6.3`
    ... which is depended on by `collision v0.1.0 (/Users/rth/code/rust_experiments/collision)`

failed to select a version for `redis-async` which could resolve this conflict
```

However, I think `cargo outdated` shouldn't panic, but rather warn that there would be a mismatch of versions. Since we're using the cargo subsystem I need to look into how that's possible.

**Comment by M1cha** [comment]
@deg4uss3r can you explain what exactly you mean by "feature"? is it a feature that it panics, or that it doesn't panic?
And why would there be different behavior between using cargo as a binary vs library?

I'd really like to help fix this because I'm unable to use cargo-outdated on a workspace with many dependencies due to this bug.

**Comment by anp** [comment]
I'm having a similar issue trying to adopt this tool for a [pretty large workspace](https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/third_party/rust_crates/Cargo.toml). First with [flate2 and zip](https://github.com/kbknapp/cargo-outdated/issues/260) and now with [nom and memchr](https://github.com/Geal/nom/issues/1330).

Would something like https://github.com/kbknapp/cargo-outdated/issues/127#issuecomment-867044136 work for your usecase? In my case I think `cargo-outdated` will be driven by a tool that can be configured with particular crates to skip updating while the latest version has these kinds of incompatibilities. There would be some manual effort required whenever someone in the ecosystem introduces this incompatibility, but it might be a decent workaround until Cargo is able to handle duplicate "incompatible" minor versions.

**Comment by deg4uss3r** [comment]
#271 is a fix for this :)

**Comment by azerupi** [comment]
I stumbled upon this issue where I got this error from cargo-outdated:

```
error: failed to select a version for `cortex-m-rt`.
    ... required by package `stm32l0xx-hal v0.8.0`
    ... which satisfies dependency `stm32l0xx-hal = "^0.8.0"` of package `loki-hal v0.1.0 (/home/azerupi/Projects/SkyHero/payloads/loki-hal)`
    ... which satisfies path dependency `loki-hal` of package `loki-pyro v0.1.0 (/tmp/cargo-outdated19LjGw)`
versions that meet the requirements `^0.6.8` are: 0.6.15

the package `cortex-m-rt` links to the native library `cortex-m-rt`, but it conflicts with a previous package which links to `cortex-m-rt` as well:
package `cortex-m-rt v0.7.1`
    ... which satisfies dependency `cortex-m-rt = "^0.7.1"` of package `loki-pyro v0.1.0 (/tmp/cargo-outdated19LjGw)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='cortex-m-rt' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `cortex-m-rt` which could resolve this conflict
```

But building with cargo works fine. I finally found that I could exclude `cortex-m-rt` and that works.
Would it be possible to suggest using the `-x` flag in the error message in case you can build fine with cargo? It took me some time to find the fix and I suppose I am not the only one. :slightly_smiling_face:
