### ISSUE TITLE
vendored-openssl would be nice on macOS and Ubuntu 18.04/20.04

### ISSUE THREAD

**Issue by HenkPoley** [kbknapp/cargo-outdated#237]
Statically link OpenSSL to work around some package versioning issues.

See here for an example: https://github.com/rust-secure-code/cargo-geiger/pull/99

Essentially put this in Cargo.toml
```
[features]
vendored-openssl = ["cargo/vendored-openssl"]
```

**Comment by deg4uss3r** [comment]
fixed in #236
