### ISSUE TITLE
cargo-outdated does not notice .cargo/config.toml when looking for config files to copy

### ISSUE THREAD

**Issue by stormbrew** [kbknapp/cargo-outdated#244]
https://github.com/kbknapp/cargo-outdated/pull/188 added copying of .cargo/config files as a resolution for https://github.com/kbknapp/cargo-outdated/issues/183 but it's allowed (and even helpful for editor purposes) to have a .toml extension on .cargo/config files. Cargo itself respects this, but cargo-outdated only copies .cargo/config.

**Comment by deg4uss3r** [comment]
closed in #263
