### ISSUE TITLE
panic if dependency from alternative registry is not available from crates.io

### ISSUE THREAD

**Issue by jonhoo** [kbknapp/cargo-outdated#247]
To reproduce:

1. Create a new project
2. Create `.cargo/config` with the following contents:
   ```
   [source.crates-io]
   replace-with = 'local-registry'
   
   [source.local-registry]
   local-registry = '/some/valid/local/registry'
   ```
3. Add a dependency in `Cargo.toml` that exists in the [local registry](https://doc.rust-lang.org/cargo/reference/source-replacement.html#local-registry-sources), but not on crates.io.
4. Run `cargo check` to see that the project builds.
5. Run `cargo outdated` and see that it panics.

Specifically, it panics here:
https://github.com/kbknapp/cargo-outdated/blob/d09073947bfc481e861a2dc08a568cefce355c1a/src/cargo_ops/temp_project.rs#L122

With the error
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/jongje/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-outdated-0.9.13/src/cargo_ops/temp_project.rs:386:127
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:62
   3: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
   4: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
   5: cargo_outdated::execute
   6: cargo_outdated::main
```

I believe the solution here is for the `unwrap_or_else` clause to have a clause for `if query_result.is_empty()`, where it instead warns that it does not support looking for updated versions in alternative registries.

**Comment by deg4uss3r** [comment]
Thanks to updated with `cargo` the newest error I get from this is: 

```
❯ cargo outdated
error: failed to select a version for the requirement `rand = "^0.8.4"`
candidate versions found which didn't match: 0.8.3
location searched: `/Users/rth/test` index (which is replacing registry `https://github.com/rust-lang/crates.io-index`)
required by package `local_registry v0.1.0 (/var/folders/zq/nwdvl5ln7bx9m_17pzr4x_1h0000gn/T/cargo-outdatedHmK3Wk)`
perhaps a crate was updated and forgotten to be re-vendored?
```

Do yo think this is clear enough now?

**Comment by jonhoo** [comment]
That does seem a lot better than the panic from before, yes!

**Comment by deg4uss3r** [comment]
Thanks I'm going to close this issue!
