### ISSUE TITLE
Failing to install via `cargo install cargo-outdated`

### ISSUE THREAD

**Issue by kurtlawrence** [kbknapp/cargo-outdated#253]
Hi there,

I could not install using `cargo install cargo-outdated`. Fails compilation of `cargo`:
![image](https://user-images.githubusercontent.com/13831379/106432686-2cec0e00-64c3-11eb-9d05-c6e53f8af573.png)

Running rust stable `1.49` targeting `stable-x86_64-unknown-linux-gnu`

**Comment by tmarkovski** [comment]
Running into the same issue.

**Comment by deg4uss3r** [comment]
please see #252

**Comment by kurtlawrence** [comment]
Thank you! Using `cargo install --locked cargo-outdated` worked.
