### ISSUE TITLE
cargo outdated gets semver wrong

### ISSUE THREAD

**Issue by Volker-Weissmann** [kbknapp/cargo-outdated#268]
Example Cargo.toml file:

```
[dependencies]
rand = "0.8.1"
lalrpop-util = "0.19.1"
proc-macro2 = "1.0.1"
```

All three dependencies are out of date, but cargo outdated reports `All dependencies are up to date, yay!`. It is only if I decrease the minor or major number that I get a warning. But a dependency outdated by a patch level is still outdated.

**Comment by deg4uss3r** [comment]
This is doing the correct thing :) 

If you check your `Cargo.lock` file you'll find `rand` at version `0.8.4` since it will update to the latest `0.8.x` version using this schema. If you want to lock it at a specific version use the following: 

```
[dependencies]
rand = "=0.8.1"
lalrpop-util = "=0.19.1"
proc-macro2 = "=1.0.1"
```

That will produce the following outdated report: 

```
❯ cargo outdated
Name          Project  Compat  Latest  Kind    Platform
----          -------  ------  ------  ----    --------
lalrpop-util  0.19.1   ---     0.19.6  Normal  ---
proc-macro2   1.0.1    ---     1.0.27  Normal  ---
rand          0.8.1    ---     0.8.4   Normal  ---
```

**Comment by Volker-Weissmann** [comment]
Ok, Thank you
