### ISSUE TITLE
Support cargo workspaces

### ISSUE THREAD

**Issue by euclio** [kbknapp/cargo-outdated#28]
It would be nice to provide a flag to view outdated dependencies for the entire workspace.

**Comment by kbknapp** [comment]
Hmm I'm not super familar with cargo workspaces yet. Let me look into this once I've knocked out a few bugs and updated the code.

**Comment by mbrubeck** [comment]
rust-lang/cargo#3704 suggests that the best way to do this is by parsing the JSON output of `cargo metadata` rather than the Cargo.lock file.  The main difference in a workspace is that there may not be a "root" package.

**Comment by SergioBenitez** [comment]
I just want to chime in and say that this would be incredibly useful! I use `cargo outdated` quite a bit. [Rocket](https://github.com/SergioBenitez/Rocket) has plenty of example crates (~30), and it would be nice to use `cargo outdated --all` (or something similar) to check whether all of their dependencies are up to date.
