### ISSUE TITLE
`cargo outdated` requires `cargo-features = ["edition2021"]` for Rust 2021, but it is stable starting in 1.56 (currently stable)

### ISSUE THREAD

**Issue by PatchMixolydic** [kbknapp/cargo-outdated#280]
I'm using rustc 1.56.0-nightly (b7404c898 2021-09-03), in which Rust 2021 is stabilized. However, cargo-outdated 0.9.17 still requires the unstable feature flag when running on a project using Rust 2021:
```console
$ cargo outdated
error: failed to load manifest for workspace member `/home/patchmixolydic/Programming/Rust/triplicata/mountain_river`

Caused by:
  failed to parse manifest at `/home/patchmixolydic/Programming/Rust/triplicata/mountain_river/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

**Comment by Stargateur** [comment]
even add `cargo-features = ["edition2021"]` doesn't work

**Comment by gdesmott** [comment]
This version should work:
`cargo install --force cargo-outdated --git https://github.com/cuviper/cargo-outdated.git --branch cargo-2021`
