### ISSUE TITLE
No matching package name found in git dependency

### ISSUE THREAD

**Issue by fpoli** [kbknapp/cargo-outdated#287]
It seems that `cargo outdated` cannot find a crate in a git dependency. `cargo build`, however, runs fine.

Project: https://github.com/viperproject/prusti-dev, commit `ca3d4dc`.

Command:
```
cargo outdated --root-deps-only --workspace
```
Output:
```
error: no matching package named `cargo-test-support` found
location searched: https://github.com/rust-lang/cargo.git#94ca096a
required by package `prusti-tests v0.2.0 (/home/fpoli/src/prusti/prusti-dev/prusti-tests)`
```

Version: `cargo-outdated v0.9.17`

**Comment by kbknapp** [comment]
This appears to be fixed with v0.10.1. Going to close, but if you need to re-open after updating please feel free to.
