### ISSUE TITLE
Provide --manifest-path

### ISSUE THREAD

**Issue by matthiasbeyer** [kbknapp/cargo-outdated#29]
Please provide `--manifest-path`, so I can automate checking with my `Makefile` in [imag](https://github.com/matthiasbeyer/imag).

:smile:

**Comment by kbknapp** [comment]
`cargo-graph` has this, I think I can just port the code over.

**Comment by kbknapp** [comment]
Alright, I've got this mostly implemented in a local branch, but I need to test it. I should be able to test and release it within the next few days.

**Comment by kbknapp** [comment]
0.3.0 is up on crates.io. I tested this and it works, ensure the paths provided are absolute, and you'll have to provide botht he `--manifest-path <path>` and `--lockfile-path <path>`.
