### ISSUE TITLE
0.10.0 tag

### ISSUE THREAD

**Issue by kpcyrd** [kbknapp/cargo-outdated#292]
hi!

any chance you could create a release for 0.10.0 on https://github.com/kbknapp/cargo-outdated/releases? :)

**Comment by bikeshedder** [comment]
The version tag for `0.9.18` is missing as well.

**Comment by messense** [comment]
+1 for this, this blocks updating Homebrew formula for cargo-outdated.

**Comment by kbknapp** [comment]
Whoops!  Will create the 0.10.1 tag once #294 merges.

**Comment by kpcyrd** [comment]
Thanks, unfortunately the commit that was tagged as `0.10.1` has this in its `Cargo.lock` and therefore doesn't build with `--locked`:

```
[[package]]
name = "cargo-outdated"
version = "0.10.0"
dependencies = [
```

**Comment by kbknapp** [comment]
Apologies! I'll fix that and rerelease first thing tomorrow.

**Comment by kbknapp** [comment]
Done :smile:
