### ISSUE TITLE
1.(Y+1).Z is misreported as incompatible

### ISSUE THREAD

**Issue by chris-morgan** [kbknapp/cargo-outdated#31]
I haven’t actually tested it myself, but from the README:

```
    Name                 Project Ver  SemVer Compat  Latest Ver
    clap                    1.2.3        1.2.5         1.4.7
```

1.4.7 *is* compatible with 1.2.3 according to SemVer. Only before 1.0.0 are all bets off for minor version number increments.

**Comment by kbknapp** [comment]
It's been a while since I dug into this code, but I believe it uses whichever semver requirement is specified (`~` vs `^`), but this is also before I knew `cargo` treats the caret differently between 0.x and 1.x.
