### ISSUE TITLE
"Latest Ver" shows an older version

### ISSUE THREAD

**Issue by sinkuu** [kbknapp/cargo-outdated#32]
`Cargo.toml`:

```toml
[dependencies]
clap = "2.19.0"
```

`cargo update; cargo outdated`:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
Checking for SemVer compatible updates...Done
Checking for the latest updates...Done
The following dependencies have newer versions available:

    Name        Project Ver  SemVer Compat  Latest Ver
    clap           2.20.0         --          2.19.3
    clap->libc     0.2.18         --          0.2.20
```

**Comment by sinkuu** [comment]
This is caused by `clap-2.20.0` downgrading `libc` (`~0.2.9` => `=0.2.18`) and unrelated to cargo-outdated (could there be a diagnostic?).

**Comment by kbknapp** [comment]
The clap specific part should be fixed with clap 2.20.1 which I'm releasing tonight. As for cargo update picking the older crate, I'm sure how I'd like to handle that one. Perhaps asserting (or using) the Project ver if it is in fact newer than the latest. Interesting how this all played out!

**Comment by dotdash** [comment]
Here's another case of `cargo outdated` getting the version ordering wrong. Most likely because `slog` uses an "interesting" version number (I have no idea how that works in SemVer tbh).

```
Checking for SemVer compatible updates...Done
Checking for the latest updates...Done
The following dependencies have newer versions available:

    Name                  Project Ver   SemVer Compat  Latest Ver
    gdk->bitflags            0.5.0           --          0.8.0
    gtk->bitflags            0.5.0           --          0.8.0
    redmine->slog            2.0.0-2.2       --          1.5.2
    redmine->slog-stdlog     2.0.0-1.0       --          1.1.0
    slog                     2.0.0-2.2       --          1.5.2
    slog-term                2.0.0-2.1       --          1.5.0
    slog-term->slog          2.0.0-2.2       --          1.5.2
```

**Comment by daboross** [comment]
@dotdash If 2.0.0-2.2 is meant as the latest version, I believe `cargo` and https://crates.io also need to be updated to account for this. https://crates.io/crates/slog shows the latest version as `slog = "1.5.2"`.

Perhaps this particular instance is better addressed as a bug in https://github.com/steveklabnik/semver?

**Comment by golddranks** [comment]
I'm getting this again, with clap:

```
The following dependencies have newer versions available:

    Name                        Project Ver  SemVer Compat  Latest Ver
    clap                           2.25.0         --          2.24.2
    clap->unicode-segmentation     1.1.0          --          1.2.0
```

`2.25.0` is shown as the latest version in `crates.io`, and it's also the version installed by `"*"`. It's also the lates version not only by the version number but also by date, so this seems like a clear bug.

**Comment by Frederick888** [comment]
@golddranks This should have been fixed in the new release. Could you please update to the latest `cargo-outdated` to see whether the issue persists?
