### ISSUE TITLE
[Feature Request]: Write to Cargo.toml

### ISSUE THREAD

**Issue by azzamsa** [kbknapp/cargo-outdated#326]
Hi

Is cargo-outdated will support writing tor Cargo.toml? such as
- `taze --write` in https://github.com/antfu/taze
- `ncu -u` in https://github.com/raineorshine/npm-check-updates

So we don't have to update the version by hand. I have read the usage doc, but couldn't find this feature.

Thanks a lot for cargo-outdated.

**Comment by Nemo157** [comment]
`cargo upgrade` from https://github.com/killercup/cargo-edit supports this already (and is currently in the process of being prepared for uplifting into `cargo` itself).

**Comment by azzamsa** [comment]
That news to me, thanks!
