### ISSUE TITLE
Update dependency on `libgit2-sys`

### ISSUE THREAD

**Issue by carlocab** [kbknapp/cargo-outdated#345]
The current dependencies pull in `libgit2-sys v0.13.5+1.4.5`, which uses version `1.4.5` of libgit2. With the [release of libgit 1.6.1](https://github.com/libgit2/libgit2/releases/tag/v1.6.1), the 1.4.x series is [no longer supported](https://github.com/libgit2/libgit2/blob/da82fb5471f0b8cf098a4711b086c08a92f5357f/SECURITY.md#supported-versions), and will thus no longer receive security fixes.

It would be good to update the crate dependencies so that `cargo-outdated` uses a maintained version of `libgit2`.

**Comment by LinusU** [comment]
There is is also [gitoxide](https://github.com/Byron/gitoxide) to consider. I believe that the author, **Byron**, is giving a lot of help to projects that wants to switch. So if this is of interest, it might be worth reaching out!

**Comment by carlocab** [comment]
Fixed in [v0.13.0](https://github.com/kbknapp/cargo-outdated/releases/tag/v0.13.0).
