### ISSUE TITLE
updating to toml 0.8

### ISSUE THREAD

**Issue by plugwash** [kbknapp/cargo-outdated#382]
Hi.

In debian we are looking to upgrade the rust-toml package from 0.7 to 0.8. While we do have a mechanism for packaging multiple versions of a crate it is something we try to avoid where possible. I was able to run the tests successfully with the dependency bumped, but there is one thing that gives me pause in the toml changelog.

>  Serialization and deserialization of tuple variants has changed from being an array to being a table with the key being the variant name and the value being the array

I would appreciate feedback on whether you consider this likely to be an issue for cargo-outdated.

**Comment by davidhewitt** [comment]
Looks like this was done in #379
