### ISSUE TITLE
Missing v0.15.0 GH release artifact

### ISSUE THREAD

**Issue by gierlachg** [kbknapp/cargo-outdated#388]
That means, among other things, that `binstall` has to fallback to installing from source.

**Comment by kpcyrd** [comment]
I also noticed this when preparing the 0.15.0 update for Arch Linux, please tag.

I'm suspecting it's either f20712d79a7ab2d15a5b5844931bde50e9d733e5 or a00bb7b0e52a6412e838a037e9c766d9216873ae.

**Comment by chenrui333** [comment]
cc @kbknapp any thoughts on this? Thanks! 🙏

**Comment by kbknapp** [comment]
Strange this issue didn't pop up in my notifications feed. I've pushed the tag so it should show up in the release page soon. I'll close this issue once it's populated on the releases page.

Thanks for the ping!
