### ISSUE TITLE
cargo-outdated reports no SemVer-compat version when there is one

### ISSUE THREAD

**Issue by euclio** [kbknapp/cargo-outdated#40]
Running the command on my project that has `clap 2.24.2` in my `Cargo.lock`, I get the following output.

```
Checking for SemVer compatible updates...Done
Checking for the latest updates...Done
The following dependencies have newer versions available:

    Name      Project Ver  SemVer Compat  Latest Ver
    clap         2.24.2         --          2.25.0
```

I would expect the SemVer Compat column to contain "2.25.0".

**Comment by Frederick888** [comment]
@euclio A new release has just been pushed to crates.io. Could you please test it again to see whether it got fixed?

**Comment by euclio** [comment]
@Frederick888 appears to be working!
