### ISSUE TITLE
install with --locked fails due to API change: update `time` to version `>=0.3.35`

### ISSUE THREAD

**Issue by KonradHoeffner** [kbknapp/cargo-outdated#401]
When I started cargo outdated today, I got an error with libgit2, so I updated it as described in the README with the --locked parameter as `cargo install cargo-outdated --locked --force`, however this results in the following error:

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/konrad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```

I'm using cargo 1.83.0-nightly (c1fa840a8 2024-08-29) installed via Rustup on Arch Linux. Current cargo-outdated version is 0.15.0.
Removing the --locked parameter fixes the issue.
I guess you can fix this by either removing the `--locked` from the README or by creating a new release with an updated lockfile.

**Comment by KonradHoeffner** [comment]
P.S.: Addressed by https://github.com/kbknapp/cargo-outdated/pull/397 and https://github.com/kbknapp/cargo-outdated/pull/398, please accept one of them and release a new version.

**Comment by barower** [comment]
`cargo install --locked cargo-outdated` still gives this error

**Comment by KonradHoeffner** [comment]
Yeah, the maintainer seems to be inactive right now, I will try to reach out.

**Comment by Z1xus** [comment]
cargo outdated got OUTDATED

**Comment by 0323pin** [comment]
BROKEN ... http://mail-index.netbsd.org/pkgsrc-changes/2024/11/30/msg311633.html

😢

**Comment by KonradHoeffner** [comment]
I have written an email twice to the author @kbknapp on October 22 and November 22 and unfortunately never gotten any response.
Does anyone here have a working communication channel to the author? :-)

**Comment by davidhewitt** [comment]
See #403, plan is to get a new release soon.
