### ISSUE TITLE
Fails to run 'cargo update'

### ISSUE THREAD

**Issue by kraai** [kbknapp/cargo-outdated#41]
When I run `cargo outdated` in a project with at least one dependency, it fails with the following error:

```
Checking for SemVer compatible updates...error: Failed to run 'cargo update' with error 'did not exit successfully'
```

When I run `cargo update`, `~/.cargo/bin/cargo update`, or `~/.rustup/toolchains/nightly-x86_64-pc-windows-msvc/bin/cargo update`, they're successful.

**Comment by kraai** [comment]
If I modify cargo-outdated so that it displays the output of `cargo update`, here's what is displayed:

```
Checking for SemVer compatible updates...error: failed to parse manifest at `C:\Users\kraaimx\AppData\Local\Temp\cargo-outdated.YL7H75Nwwc8B\Cargo.toml`

Caused by:
  can't find `test` bin, specify bin.path
error: Failed to run 'cargo update' with error 'did not exit successfully'
```

**Comment by Dushistov** [comment]
I have the same issue

**Comment by golddranks** [comment]
I have had the same issue for some days too.

**Comment by brendanzab** [comment]
Same issue too! :(
