### ISSUE TITLE
What does "RM" mean in the output?

### ISSUE THREAD

**Issue by steveklabnik** [kbknapp/cargo-outdated#46]
```text
Name                                   Project Ver     SemVer Compat  Latest Ver
aho-corasick->memchr                      0.1.11            RM            RM
```

Might be nice to have this explained somewhere.

**Comment by Frederick888** [comment]
Yeah, improving the documents would be a must. Some help messages are needed to be updated as well.

As far I could see, the new `0.4.0` release works slightly different in terms of:
1. Packages that are removed after an update are marked as `RM`
0. `--depth 0` literally means checking only the root now (note that there was a related issue just got fixed #47)

**Comment by Frederick888** [comment]
And by the way, is the provided example an actual output? Coz I just had a glance at `aho-corasick` and found that `memchr` was still in its dependency list.

**Comment by steveklabnik** [comment]
This is actual output, yeah. I forget what project I used it on.... gah!

**Comment by Frederick888** [comment]
@steveklabnik I'm working on #51 and `RM` has been replaced by `Removed`. Apparently it turned out that saving several characters was completely unnecessary and even confusing. :sweat_smile:

This label is what you get when a dependency is removed from the dependency tree after an update.

**Comment by casey** [comment]
I was a little confused by `Removed`. I think `Superfluous` or `Unnecessary` might be more precise.
