### ISSUE TITLE
doesn't work when dependency is in path

### ISSUE THREAD

**Issue by dimbleby** [kbknapp/cargo-outdated#50]
```
$ cargo outdated
error: Failed to run 'cargo update' with error 'did not exit successfully'
```

I saw this with [`c-ares`](https://github.com/dimbleby/rust-c-ares).  

I believe the difficulty is dealing with [this](https://github.com/dimbleby/rust-c-ares/blob/664f295e5c8d73a04babf23003dc66bcbe9e517e/Cargo.toml#L17): `cargo outdated` copies my `Cargo.toml` into a temporary directory but does not copy `c-ares-sys/Cargo.toml`.  That's why `cargo update` fails.

**Comment by Frederick888** [comment]
Related to #28 I think.

**Comment by durka** [comment]
#51 fixes this for me.

**Comment by WiSaGaN** [comment]
This seems to be a regression from 0.3.0 for me.

**Comment by Frederick888** [comment]
@WiSaGaN Could you please try #51 ?

**Comment by stusmall** [comment]
Not OP but facing the same issue.  #51 fixed it for me.

**Comment by WiSaGaN** [comment]
It seems we still need to implement the support for relative path like
```
[dependencies.foo]
version = "*"
path = "../foo"
```
