### ISSUE TITLE
Support JSON output format

### ISSUE THREAD

**Issue by Frederick888** [kbknapp/cargo-outdated#55]
Print out the dependency tree to a JSON

**Comment by Michael-F-Bryan** [comment]
I was playing around with creating a bot to iterate over each crate in crates.io and run `cargo outdated` on them. The idea being we can then have a second bot which will create PRs to help other people keep their dependencies up to date.

I imagine either having an option for machine-readable or exposing `cargo-outdated`'s internals as a library would make this sort of use case a lot easier.

**Comment by deg4uss3r** [comment]
Hey guys, just changed jobs over and using this issue to get back into things :D 

I have a rough draft to this issue in [json_feature](https://github.com/deg4uss3r/cargo-outdated/tree/json_feature) hoping this helps :)
