### ISSUE TITLE
Loop through all workspace members if executed against a virtual manifest

### ISSUE THREAD

**Issue by Frederick888** [kbknapp/cargo-outdated#58]
Mentioned [here](https://github.com/kbknapp/cargo-outdated/pull/51#issuecomment-326521356) by @Keats.

And the suggested format is:

```
site
================
Name          Current  Compat  Latest    Kind         Platform
clap          2.20.0   2.20.5  2.26.0    Normal       ---

rendering
================
Name          Current  Compat  Latest    Kind         Platform
clap          2.20.0   2.20.5  2.26.0    Normal       ---
```

**Comment by euclio** [comment]
Is this exposed anywhere in case the workspace root is *not* a virtual manifest? I'd still like to loop over all members of the workspace.

**Comment by Frederick888** [comment]
@euclio Fair point... I was thinking that if it was not a virtual manifest, then other members should be the dependencies of the root package. But we indeed can have members that are not related to the root package, can't we?

Could you please file another issue for this?
