### ISSUE TITLE
`--exit-code` and `--color` do not work

### ISSUE THREAD

**Issue by Frederick888** [kbknapp/cargo-outdated#63]

**Comment by Frederick888** [comment]
Related to kbknapp/clap-rs#1050

**Comment by pravic** [comment]
Is this the same?

> $ cargo outdated --color always
error: The argument '--color <color>' requires 1 values, but 2 were provided
USAGE:
    cargo outdated --color <color> --exit-code <NUM>

**Comment by Frederick888** [comment]
@pravic Yes, I think so.
