### ISSUE TITLE
Consistent failure with the same package

### ISSUE THREAD

**Issue by Keats** [kbknapp/cargo-outdated#75]
Version: 0.5.1

This [Cargo.toml](https://github.com/Keats/tera/blob/v0.11/Cargo.toml) always fail with the following error:

```
error: no matching package named `pest_derive` found (required by `tera`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: *
```

**Comment by Frederick888** [comment]
I think this is related to rust-lang/cargo#2222. I still have no idea how to capture the latest pre-release without calling `crates.io` APIs. In your case specifically, because `pest_derive` has no stable release yet, `cargo` simply fails due to "no matching package" with the wildcard requirement.
